# Generated by Django 5.2.12 on 2026-03-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('Random Thoughts', 'Random Thoughts'), ('School', 'School'), ('Personal', 'Personal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
